### ISSUE TITLE
Find source of error in TroughWagner Daggett solar positions

### ISSUE THREAD

**Issue by paul-scott** [SolarTherm/SolarTherm#34]
When using the Daggett weather data, the solar positions go outside bounds of acos calculation.

**Comment by jdpipe** [comment]
Sounds like a problem to do with the sign convention in your sun position calculator. Probably the sign convention should be different depending on the hemisphere to avoid unnecessary discontinuities from arc-trig functions.

**Comment by paul-scott** [comment]
Works perfectly with same time steps in a separate model.  Seems to be a slightly different numerical values when used in with the generic model.  In practice hard to test for this kind of thing as unit testing the solar positions in isolation won't show this error.

In the TroughWagner model the acos argument takes on a value of -1.000000000000000444 when it needs to be in interval [-1, 1].  Will try calling the trusty old max to make sure this remains in interval.  Should only trigger a couple of times a day.
