### ISSUE TITLE
Round 2 of financial calcs

### ISSUE THREAD

**Issue by paul-scott** [SolarTherm/SolarTherm#36]
What additional financial/performance calculations do we want?  Should we prioritise some of these over the short term?

- depreciation
- yearly performance degradation
- PPA
- loans
- taxes
- incentives
- NPV
- IRR
- etc...

**Comment by jdpipe** [comment]
For now, I think a simple LCOE with no consideration of taxes etc is appropriate. LCOE is a metric to evaluate the costs independent of project finance, economic context, etc. LCOE is affected by the magnitude of O&M and capital costs, together with annual output and discount rate. Nice and simple.

More complex models bring in the things you mentioned. I don't see them as being short-term needs.

A nice reference scenario for LCOE across various technologies: http://www.co2crc.com.au/dls/Reports/LCOE_Report_final_web.pdf

**Comment by paul-scott** [comment]
Low priority for now so closing.
