### ISSUE TITLE
Memory leak in st_table_init

### ISSUE THREAD

**Issue by tbeu** [SolarTherm/SolarTherm#63]
If table_init is non-zero in https://github.com/SolarTherm/SolarTherm/blob/a48cd076628d2de730e6d9b93e72164521bd18fc/SolarTherm/Resources/Include/st_tables.c#L33-L34
the allocated memory of the external object table is leaking.

**Comment by jdpipe** [comment]
thanks for the report! you're right -- if malloc fails then we will be leaking. did you check this with valgrind etc, or just notice it from the source?

**Comment by tbeu** [comment]
> Did you check this with valgrind etc, or just notice it from the source?

Can't remember exactly, but probably with some tool support.

**Comment by jdpipe** [comment]
I think this should be fixed in commit 17782997de0c3bd330060d6fb8c5bfcf2759b7de.
