### ISSUE TITLE
lost pointer if in on-the-fly surrogate

### ISSUE THREAD

**Issue by jdpipe** [SolarTherm/SolarTherm#90]
Hi Philipe -- here I think that if the file is opened, you will have a pointer 'g' which is being lost be reassigning `fopen(...)` to `g` a second time. Need to `fclose` first, or consider using `freopen`?
https://github.com/SolarTherm/SolarTherm/blob/28bb2fefffa2f83d5b54c318aea9b651999f7dda/src/modelica/st_on_the_fly_surrogate.c#L2946

**Comment by philgun** [comment]
Already updated
